#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 28, 2018 02:39:18 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Identifiant_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Gestions_des_mots_de_passe (root)
    Identifiant_support.init(root, top)
    root.mainloop()

w = None
def create_Gestions_des_mots_de_passe(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Gestions_des_mots_de_passe (w)
    Identifiant_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Gestions_des_mots_de_passe():
    global w
    w.destroy()
    w = None


class Gestions_des_mots_de_passe:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("600x328+353+152")
        top.title("Gestions des mots de passe")
        top.configure(relief="groove")
        top.configure(background="#d9d9d9")



        self.ButtonConnexion = Button(top)
        self.ButtonConnexion.place(relx=0.15, rely=0.76, height=34, width=108)
        self.ButtonConnexion.configure(activebackground="#d9d9d9")
        self.ButtonConnexion.configure(activeforeground="#000000")
        self.ButtonConnexion.configure(background="#d9d9d9")
        self.ButtonConnexion.configure(command=Identifiant_support_1.Connexion)
        self.ButtonConnexion.configure(disabledforeground="#a3a3a3")
        self.ButtonConnexion.configure(foreground="#000000")
        self.ButtonConnexion.configure(highlightbackground="#d9d9d9")
        self.ButtonConnexion.configure(highlightcolor="black")
        self.ButtonConnexion.configure(pady="0")
        self.ButtonConnexion.configure(text='''Connexion''')
        self.ButtonConnexion.configure(width=108)

        self.ButtonAnnuler = Button(top)
        self.ButtonAnnuler.place(relx=0.43, rely=0.76, height=34, width=93)
        self.ButtonAnnuler.configure(activebackground="#d9d9d9")
        self.ButtonAnnuler.configure(activeforeground="#000000")
        self.ButtonAnnuler.configure(background="#d9d9d9")
        self.ButtonAnnuler.configure(disabledforeground="#a3a3a3")
        self.ButtonAnnuler.configure(foreground="#000000")
        self.ButtonAnnuler.configure(highlightbackground="#d9d9d9")
        self.ButtonAnnuler.configure(highlightcolor="black")
        self.ButtonAnnuler.configure(pady="0")
        self.ButtonAnnuler.configure(text='''Annuler''')
        self.ButtonAnnuler.configure(width=93)

        self.ButtonQuitter = Button(top)
        self.ButtonQuitter.place(relx=0.68, rely=0.76, height=34, width=98)
        self.ButtonQuitter.configure(activebackground="#d9d9d9")
        self.ButtonQuitter.configure(activeforeground="#000000")
        self.ButtonQuitter.configure(background="#d9d9d9")
        self.ButtonQuitter.configure(disabledforeground="#a3a3a3")
        self.ButtonQuitter.configure(foreground="#000000")
        self.ButtonQuitter.configure(highlightbackground="#d9d9d9")
        self.ButtonQuitter.configure(highlightcolor="black")
        self.ButtonQuitter.configure(pady="0")
        self.ButtonQuitter.configure(text='''Quitter''')
        self.ButtonQuitter.configure(width=98)

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.EntryIndentifiant = Entry(top)
        self.EntryIndentifiant.place(relx=0.42, rely=0.4, relheight=0.09
                , relwidth=0.31)
        self.EntryIndentifiant.configure(background="white")
        self.EntryIndentifiant.configure(disabledforeground="#a3a3a3")
        self.EntryIndentifiant.configure(font="TkFixedFont")
        self.EntryIndentifiant.configure(foreground="#000000")
        self.EntryIndentifiant.configure(insertbackground="black")
        self.EntryIndentifiant.configure(width=184)

        self.EntryMotsDePass = Entry(top)
        self.EntryMotsDePass.place(relx=0.42, rely=0.55, relheight=0.09
                , relwidth=0.31)
        self.EntryMotsDePass.configure(background="white")
        self.EntryMotsDePass.configure(disabledforeground="#a3a3a3")
        self.EntryMotsDePass.configure(font="TkFixedFont")
        self.EntryMotsDePass.configure(foreground="#000000")
        self.EntryMotsDePass.configure(insertbackground="black")
        self.EntryMotsDePass.configure(width=184)

        self.LabelIdentifiant = Label(top)
        self.LabelIdentifiant.place(relx=0.15, rely=0.4, height=41, width=159)
        self.LabelIdentifiant.configure(background="#d9d9d9")
        self.LabelIdentifiant.configure(disabledforeground="#a3a3a3")
        self.LabelIdentifiant.configure(font=font9)
        self.LabelIdentifiant.configure(foreground="#000000")
        self.LabelIdentifiant.configure(highlightbackground="#646464646464")
        self.LabelIdentifiant.configure(text='''Identifiant''')
        self.LabelIdentifiant.configure(width=159)

        self.LabelMotDePass = Label(top)
        self.LabelMotDePass.place(relx=0.17, rely=0.55, height=31, width=133)
        self.LabelMotDePass.configure(background="#d9d9d9")
        self.LabelMotDePass.configure(disabledforeground="#a3a3a3")
        self.LabelMotDePass.configure(font=font9)
        self.LabelMotDePass.configure(foreground="#000000")
        self.LabelMotDePass.configure(text='''Mot de passe :''')

        self.LabelTitre = Label(top)
        self.LabelTitre.place(relx=0.08, rely=0.15, height=31, width=497)
        self.LabelTitre.configure(background="#d9d9d9")
        self.LabelTitre.configure(disabledforeground="#a3a3a3")
        self.LabelTitre.configure(font=font9)
        self.LabelTitre.configure(foreground="#000000")
        self.LabelTitre.configure(relief=SUNKEN)
        self.LabelTitre.configure(text='''Vive la formation sur Python 3''')
        self.LabelTitre.configure(width=497)






if __name__ == '__main__':
    vp_start_gui()


